"""add username and password to students

Revision ID: 3e1a9d8c7ac9
Revises: 90df7f7ca42a
Create Date: 2026-09-09 20:03:47.051662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1a9d8c7ac9'
down_revision: Union[str, Sequence[str], None] = '90df7f7ca42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'students', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'password_hash')
    op.drop_column('students', 'username')
    # ### end Alembic commands ###
