"""add complaint timestamps

Revision ID: 90df7f7ca42a
Revises: 9682a07fc00b
Create Date: 2026-09-04 20:46:12.199245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90df7f7ca42a'
down_revision: Union[str, Sequence[str], None] = '9682a07fc00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('complaints', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'updated_at')
    op.drop_column('complaints', 'created_at')
    # ### end Alembic commands ###
